/** Declaration file generated by dts-gen */
declare module 'xqlint' {

    export function JSONiqLexer(): any;

    export function XQLint(source: string, opts: any): any;

    export function XQueryLexer(): any;

    export function createStaticContext(processor: any): any;

    export namespace JSONiqLexer {
        const prototype: {
        };

    }

    export namespace XQLint {
        const prototype: {
        };
    }

    export namespace XQueryLexer {
        const prototype: {
        };

    }

    export namespace createStaticContext {
        const prototype: {
        };

    }

    export interface pos {
        line: number,
        col: number
    }

    export interface completion {
        meta: string,
        name: string,
        value: string
    }

}
